repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.9
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8
-   repo: local
    hooks:
    - id: tests
      name: run-tests
      entry: make test
      language: system
# -   repo: local
#     hooks:
#     - id: coverage-badge
#       name: generate_coverage_badge
#       entry: make generate_coverage_badge
#       language: system