ocpProject: dedrr
containerId: prodflask
containerRoute: prodflask-dedrr.statwb.eu.novartis.net
gitRepository: http://gogs-cicd.statwb.eu.novartis.net/dbrrt/flask-poetry-ocp.git
gitBranch: master
gitCredentialsId: gogs-repo-pw
podReplicas: 5
stage: production